# This rule is not used by the project myresource-kb itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to mygroup.pratap-t.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: myresource-kb
    app.kubernetes.io/managed-by: kustomize
  name: myresource-viewer-role
rules:
- apiGroups:
  - mygroup.pratap-t.dev
  resources:
  - myresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mygroup.pratap-t.dev
  resources:
  - myresources/status
  verbs:
  - get
